version: "3.1"
services:
    identity:
        container_name: identity
        image: identity:1.0.0-rc
        build:
            context: ./../
            dockerfile: Docker/${DOCKERFILE}
        environment:
            - PORT=${PORT}
        ports:
            - ${PORT}:80
        volumes:            
            - ./../:/source